[project]
name = "mariadb-maintenance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "jinja2>=3.1.5",
    "mariadb>=1.1.11",
]
